# Generated by Django 5.1 on 2024-10-13 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='door_item',
            fields=[
                ('item_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('item_image', models.FileField(upload_to='door_image')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('shop_name', models.TextField()),
                ('address', models.TextField()),
                ('mobile_number', models.TextField()),
                ('username', models.TextField()),
                ('email', models.EmailField(default='', max_length=254)),
                ('passcode', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sub_catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_item', models.TextField()),
                ('item_size', models.TextField()),
                ('item_price', models.TextField()),
                ('item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.door_item')),
            ],
        ),
    ]
